[[override]]
  name = "k8s.io/api"
  revision = "release-1.14"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "release-1.14"

[[override]]
  name = "k8s.io/client-go"
  # Compatibility: Kubernetes main repo, 1.14 branch
  revision = "release-11.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.2.2"
