[[override]]
  name = "k8s.io/api"
  revision = "159aefb8556bb8ed4be7631461d1558546d304db" # release-1.14

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "c5d2f014d689246b84637774317fa0288dd3129b" # release-1.14

[[override]]
  name = "k8s.io/client-go"
  # Compatibility: Kubernetes main repo, 1.14 branch, release-11.0
  revision = "8e412805300829bc5a39e63eaccfc8a3355e4797"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.2.2"
