apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-from-snap-rbd
spec:
  storageClassName: my-ceph-sc.ember-csi.io
  dataSource:
    name: my-ceph-vs
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
