---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: my-ceph-vs
spec:
  snapshotClassName: my-ceph-vsc
  source:
    name: ember-csi-pvc
    kind: PersistentVolumeClaim
