---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ember-csi-operator
  namespace: ember-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ember-csi-operator
  template:
    metadata:
      labels:
        name: ember-csi-operator
    spec:
      serviceAccountName: ember-csi-operator
      containers:
        - name: ember-csi-operator
          image: docker.io/embercsi/ember-csi-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - ember-csi-operator
          args: ["-v=3"]
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: X_EMBER_OPERATOR_CLUSTER
              value: k8s-v1.13
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ember-csi-operator"

