---
apiVersion: "ember-csi.io/v1alpha1"
kind: "EmberCSI"
metadata:
  name: "my-kaminario"
spec:
  config:
    envVars:
      X_CSI_PERSISTENCE_CONFIG:       '{"storage":"crd"}'
      X_CSI_BACKEND_CONFIG :          '{"name":"kaminario","driver":"KaminarioISCSI","san_ip":"1.2.3.4","use_multipath_for_image_xfer": "true","san_login":"someusername","san_password":"somesecretpassword"}'

