---
apiVersion: ember-csi.io/v1alpha1
kind: EmberCSI
metadata:
  name: my-qnap
spec:
  config:
    envVars:
      X_CSI_EMBER_CONFIG:
        plugin_name: my-qnap
      X_CSI_PERSISTENCE_CONFIG:
        storage: crd
      X_CSI_BACKEND_CONFIG:
        name: qnap
        driver: QnapISCSI
        use_multipath_for_image_xfer: true
        qnap_management_url: https: //w.x.y.z: 443
        iscsi_ip_address: w.x.y.z
        qnap_storage_protocol: iscsi
        qnap_poolname: Storage Pool 1
        san_login: admin
        san_password: toomanysecrets
