---
apiVersion: ember-csi.io/v1alpha1
kind: EmberCSI
metadata:
  name: my-solidfire
spec:
  config:
    envVars:
      X_CSI_EMBER_CONFIG:
        plugin_name: my-solidfire
      X_CSI_PERSISTENCE_CONFIG:
        storage: crd
      X_CSI_BACKEND_CONFIG :
        name: solidfire
        driver: SolidFire
        san_ip: 1.2.3.4
        san_login: someusername
        san_password: somesecretpassword
        sf_allow_template_caching: false
        image_volume_cache_enabled: true
        volume_clear: zero

