---
apiVersion: ember-csi.io/v1alpha1
kind: EmberCSI
metadata:
  name: my-xtremio-iscsi
spec:
  config:
    envVars:
      X_CSI_EMBER_CONFIG:
        plugin_name: my-xtremio-iscsi
      X_CSI_PERSISTENCE_CONFIG:
        storage: crd
      X_CSI_BACKEND_CONFIG :
        name: xtremio
        driver: XtremIOISCSI
        san_ip: 1.2.3.4
        use_multipath_for_image_xfer: true
        xtremio_cluster_name: exampleclustername
        san_login: someusername
        san_password: somesecretpassword
